name: Deploy Storybook and Publish UI Kit

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write
  packages: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          registry-url: https://npm.pkg.github.com
          scope: "@marianaLinoGit"

      - name: Install
        run: npm ci

      - name: Build UI Kit
        run: npm run build model-ui-kit

      - name: Publish UI Kit
        run: npm publish dist/ui-kit
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Storybook
        run: npm run build-storybook

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static

      - name: Deploy Storybook
        id: deployment
        uses: actions/deploy-pages@v4
